### ISSUE TITLE
Allow setting custom zmqpubhashblock port

### ISSUE THREAD

**Issue by pajasevi** [cculianu/Fulcrum#102]
Since it's possible to run ZMQ channels on different ports than default (and some setups like Samourai Dojo use it like this), it would be great if it would be possible to set `zmqpubhashblock` value either via conf file or CLI (or both ideally) so Fulcrum can leverage this feature even if not running on default port.

I am not skilled in C++, otherwise I would be happy to make a PR.

**Comment by cculianu** [comment]
Fulcrum should auto-detect it by querying the bitcoind instance via RPC for the port.  It queries RPC endpoint `getzmqnotifications`.  So it auto-detects it...

It's not working?

**Comment by pajasevi** [comment]
@cculianu Oh, I haven't realized this as `getzmqnotifications` is somewhat undocumented. Then there is no problem and my concerns were unnecessary.

Thank you for clearing that out.

**Comment by anonqoder** [comment]
Apparently it's not working

```
May 20 15:56:44 endor Fulcrum[110112]: [2022-05-20 15:56:44.931] <Controller> zmqHashBlockStart: start failed
May 20 15:56:44 endor Fulcrum[110112]: [2022-05-20 15:56:44.932] <Controller> zmqHashBlockNotifier: Invalid argument
```

My ```bitcoind```  is version ```23.0```

**Comment by cculianu** [comment]
Hmm I'm on Core 23.0.0 and it is definitely working for me.  Try running `Fulcrum` with the `-d` option or `debug=true` in the conf file to see additional debug output.  That "Invalid argument" is coming form the zmq lib somehow.

What is your setup?  What machine are you on?  Distro?

**Comment by anonqoder** [comment]
I am running Fedora 35, compiled Fulcrum from sources. 

``` 
Fulcrum 1.6.0 (Release a92ee16)
compiled: gcc 11.3.1
jemalloc: unavailable
Qt: version 6.2.3
rocksdb: version 6.22.1-unk
simdjson: version 0.6.0
ssl: OpenSSL 1.1.1n  FIPS 15 Mar 2022
zmq: libzmq version: 4.3.4, cppzmq version: 4.7.1
```

Debug output:

```
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.106] <Controller> (Debug) "hashblock" topic address: tcp://*:38330
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.202] <Controller> Block height 737532, up-to-date
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.203] SrvMgr: starting 1 service ...
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.203] (Debug) TcpSrv 0.0.0.0:52001 starting thread
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.203] Starting listener service for TcpSrv 0.0.0.0:52001 ...
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.203] Service started, listening for connections on 0.0.0.0:52001
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.203] <TcpSrv 0.0.0.0:52001> (Debug) started ok
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.204] <Controller> Starting ZMQ Notifier (hashblock) ...
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.204] <ZMQ Notifier (hashblock)> (Debug) thread started for addr: tcp://*:38330 topic: hashblock (procaddress: inproc://7f4d44005ff0b9c10bfc)
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.205] <ZMQ Notifier (hashblock)> (Debug) thread caught exception: Invalid argument
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.205] <ZMQ Notifier (hashblock)> (Debug) thread exiting after processing 0 msgs, 0 bytes ...
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.205] <Controller> (Debug) ZMQ: Joining thread ...
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.205] <Controller> (Debug) ZmqSubNotifier::Pvt::~Pvt()
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.205] <Controller> zmqHashBlockStart: start failed
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.206] <Controller> zmqHashBlockNotifier: Invalid argument
May 23 06:42:57 Fulcrum[514745]: [2022-05-23 06:42:57.207] <Controller> (Debug) BitcoinD verified to have txindex enabled
```

I have this port open

```
$ netstat -plnt | grep ":38330"
tcp6       0      0 :::38330                :::*                    LISTEN      3579/bitcoind      
```

**Comment by cculianu** [comment]
You should just set `zmqpubhashblock=tcp://0.0.0.0:38330` in your bitcoin.conf...

**Comment by anonqoder** [comment]
I have ```main.zmqpubhashblock=tcp://*:38330```

**Comment by cculianu** [comment]
Well that's not a known URL to zmq.. since clearly ZMQ rejects it if given it... please change that `*` to `0.0.0.0`...

**Comment by cculianu** [comment]
Or, if that `*` is actually a valid thing in ZMQ -- can you point me to some docs that discuss it? I can add it to Fulcrum as a "magical pattern" that gets transformed to the known IP address of the server...

**Comment by anonqoder** [comment]
https://zguide.zeromq.org/docs/chapter2/

**Comment by cculianu** [comment]
Ah, ok, thanks. So it is indeed a valid pattern when binding.  yeah -- I'll have to add a magical pattern interpreter to remap that to the known URL of bitcoind.

In the meantime just change your bitcoin.conf to read: `main.zmqpubhashblock=tcp://0.0.0.0:38330` which is equivalent.,, and which Fulcrum recognizes.

**Comment by cculianu** [comment]
Actually @anonqoder since you compiled Fulcrum yourself — I’ll push a commit later today (I’m on USA time) and maybe when you have time you can rebuild from master and when you do, restore the previously non-working `tcp://*:xxxx` syntax to bitcoind conf and let me know if that’s working?

I’ll ping u here when I push the commit …

I mean I will test it too of course here but good to see others having it work on their setups…

**Comment by cculianu** [comment]
Hey @anonqoder I just pushed commit [916b434](https://github.com/cculianu/Fulcrum/commit/916b43495fd4b45cd2771d2591da39ef9d07224c) which fixes this issue.  Want to try building off latest master and reverting your `bitcoin.conf` to the previous `tcp://*:38330` notation to verify it works now?  It works here for me locally now.

TIL: ZMQ also has `*` notation for the URL! Thanks for reporting this issue.  Fulcrum grows stronger!
