### ISSUE TITLE
Unify admin port in example config files

### ISSUE THREAD

**Issue by zx9r** [cculianu/Fulcrum#103]
fulcrum-example-config.conf suggest admin port 9000 while in fulcrum-quick-config.conf is set to 8000

Documentation of FulcrumAdmin uses port 8000

So I suggest using also port 8000 in the config file fulcrum-example-config.conf

**Comment by cculianu** [comment]
Ah, thanks for the suggestion.  I went ahead and set the example.conf to 8000 as a suggested value.  It's in latest master now.  Closing this...
