### ISSUE TITLE
Question about using Electrum Server 

### ISSUE THREAD

**Issue by caheredia** [cculianu/Fulcrum#113]
This is my first attempt at using an Electrum Server with a Bitcoin core node. My question is if I previously used my wallets with the node should I go and delete the wallet.dat files from the node? From what I understand connecting my wallet (Sparrow) to the Fulcrum server will prevent anyone from seeing what wallets I'm using. But will having those old wallet.dat files on the node remove privacy?

**Comment by cculianu** [comment]
Strictly speaking no, the wallet files are safe and are 100% inaccessible from Sparrow and Fulcrum.  Just make sure your node's HTTP-RPC port is *NOT* reachable from the internet!!!  They should be bound to a private IP or to localhost (if Fulcrum is running on same box).

However if you want to be paranoid and especially if the wallets have money in them, take them out of the datadir.  But this is not necessary really if the HTTP-RPC is definitely not listening on any public IP and is not reachable from outside your firewall.

**Comment by caheredia** [comment]
That makes sense, thanks!  I believe mine it set to only accept connections from the local ips. 

```shell
# this binding allows us to access the service outside of localhost
bind=0.0.0.0
rpcbind=0.0.0.0
rpcport=8332

rpcallowip=127.0.0.1
rpcallowip=172.0.0.0/8
rpcallowip=192.168.1.0/24
rpcallowip=10.13.13.0/24
```

**Comment by cculianu** [comment]
Ok, great. Yes that list of IPs is all private networks (not internet IPs). It should be fine.
