### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by prusnak** [cculianu/Fulcrum#117]
It seems that Fulcrum has some nice unreleased features that are only available from master (`fast-sync` option, etc.).

Maybe it's time to publish new release?

**Comment by cculianu** [comment]
I definitely do plan on doing a release this week. I just added Litecoin support (no real mweb support though on account of a lack of client software that understands it). 

However, `--fast-sync` is indeed available in released form.  1.6.0 release has `--fast-sync`...
