### ISSUE TITLE
Missing 1.7.0 ARM build?

### ISSUE THREAD

**Issue by pajasevi** [cculianu/Fulcrum#121]
Hey there. In your recent [1.7.0 release notes](https://github.com/cculianu/Fulcrum/releases/tag/v1.7.0), you state that there is an ARM build available, yet no file is provided in the assets section. I was just wondering if that is by mistake if there's some issue.

Having an ARM build ready for 1.6.0 was very nice feature.

**Comment by cculianu** [comment]
Oh. I forgot to do that. HA! Ok.. will do now. :)

**Comment by cculianu** [comment]
Ok, done and added to latest release.  Just refresh the page and it should show up. Thanks for reminding me and sorry for forgetting.

**Comment by pajasevi** [comment]
Thank you 👍
