### ISSUE TITLE
Add feature: hashed rpcauth in .config

### ISSUE THREAD

**Issue by Schnema1** [cculianu/Fulcrum#124]
Hi Calin Culianu

Thanks for your amazing work. I came across your site because of the video series of "Ministry of Nodes". As I am not a developer myself, I cannot add the peace of code I would like to see. So, I head out with a suggestion to you. 

In the config file the connection to bitcoind must be set. I do not like to have the password in clear text there. Since bitcoind itself provided a nice solution to address this problem, it would be nice to see it here too. The added the rpcauth.py file which creates a hashed login. You can find it here.
https://github.com/bitcoin/bitcoin/tree/master/share/rpcauth

Can you or another developer please implement this feature, so we can add the hashed value in the fulcrum.config file?

Example Output:
String to be appended to bitcoin.conf:
rpcauth=Test:260354875a51bb3387e3b5efb720ef3a$71ea4d97496f49add0af666a5844cb5aa4acaca47fa9e47b576e85c3abbee16e
Your password:
Test

It would be nice to add rpcauth= xxxxx.... to fulcrum.config

Thank you 
Marc

**Comment by cculianu** [comment]
Ah yes.   You know, I have never once used this feature of bitcoind -- I had to read the sourcecode for it just now to understand how it works.  It just takes the salt and the password and hashes them together using HMAC_SHA256.  I think I can implement this quickly.  I'll do so and add it as an optional conf file arg `rpcauth=`.

**Comment by cculianu** [comment]
Ok, I read the sourcecode again.

You know this mechanism would still end up with a plaintext password in the Fulcrum.conf file, actually.  There is nothing for me to implement!  I think you misunderstand how `rpcauth=` works.

Let me explain:

The way `rpcauth=` works is the Fulcrum server takes your plaintext password (which it must know!), and just sends that to the server anyway as basically plaintext.  The server-side then takes that password it received and hashes it with the salt, and compares the result to the stuff after the `$` in the `bitcoind.conf`.

I think you misunderstand how `rpcauth=` works.  The only thing this mechanism allows you to do is **not hard-code the password in the bitcoind.conf file**!.  You still must *know* the password on the client-side (and thus must have it there in plaintext in fulcrum.conf).

There is nothing for me to implement.  I challenge you right now to generate an `rpcauth=` line for bitcoind, using say username `foo` and password `bar`.  Paste the hex it tells you to into `bitcoind.conf`, e.g.: `rpcauth=foo:010203$02030405`, and continue to specify `rpcuser=foo` `rpcpassword=bar` in fulcrum.conf.

Nothing on the client side needs to change for `rpcauth=` on the bitcoind side is what I am trying to tell you.  I hope this explanation is clear.

I will close this issue now.

**Comment by Schnema1** [comment]
Thank you for investigating the question! Your precision does help me a lot in order to understand the process.

**Comment by cculianu** [comment]
Yeah basically on the client side in fulcrum you leave things as-is. And on the server side in bitcoind you switch from using rpcsuser/rpcpass to using rpcauth (and you use that script you linked-to to generate the rpcauth hash).

Let me know how it works out.

**Comment by Schnema1** [comment]
Yeah, on bitcoind side I already make use of the rpcauth hash. This is why I asked the question here. But it's all good, I understand your explain above.
