### ISSUE TITLE
Database directory "datadir" path format 

### ISSUE THREAD

**Issue by Francisco-DAnconia** [cculianu/Fulcrum#128]
Is there anyway to have a space in the path name to the database?
Running on macOS Monterey.

I wanted to setup the Fulcrum database similar to bitcoin folder structure. Bitcoin's default on macOS is mainet in **~/Library/Application Support/Bitcoin/blocks** and testnet in **~/Library/Application Support/Bitcoin/testnet3/blocks**.

I tried many conceivable settings in the fulcrum.conf file to no avail. 

Use of single quotes, double quotes, full paths, user home folder relative paths, "~" or escaping with "\" (like in the terminal) all resulted with a path starting in working directory of Fulcrum. Even prepending /../ would create a ".." folder next to the executable before moving up one folder level.

All my attempts resulted in something like this as the database location: **/usr/local/bin/"/Users/userA/Library…**

I expected the database to land here: **~/Library/Application Support/Fulcrum/blocks** or **~/Library/Application Support/Fulcrum/testnet3/blocks.**

**Comment by cculianu** [comment]
`~` expansion is just a convention used by shells such as `bash`, `sh`, `csh`, etc.  It has no real meaning outside of shell language, and is not necessarily supported by most applications, such as even Bitcoin Core itself.

Fulcrum does not expand paths.  As for spaces.. they should work.  Fulcrum does just take the whole string it sees.  So you would have to do `/Users/userA/Library/Application Support/Fulcrum` or something like that.  That doesn't work?  Sorry I'm having trouble understanding what works an what doesn't work...

**Comment by Francisco-DAnconia** [comment]
> As for spaces.. they should work. Fulcrum does just take the whole string it sees. So you would have to do `/Users/userA/Library/Application Support/Fulcrum` or something like that.

Thanks.

Perhaps it was user error.  I just tried the testnet path to Application Support and it works. 

I'm in the middle of a mainnet index (last time I had a fatal failure with the utxo db). I'll experiment a little more after that finishes - my best guess is I accidentally added quotes on the testnet path.
