### ISSUE TITLE
Dualstack IPv4 IPv6

### ISSUE THREAD

**Issue by petrkr** [cculianu/Fulcrum#130]
How to make it listen on both IPv4 and IPv6?
I tried ssl = :::50002 but it listen only on IPv6 and does not accept IPv4. 0.0.0.0:50002 of course only IPv4.. I Also tried space, comma, interface but nothing works...

I know I can do some workaround with HAproxy or something on top of it. but would be nice to have it natively

**Comment by EchterAgo** [comment]
I specify each port like this:

```
tcp = 0.0.0.0:50001
tcp = ::0:50001
```

This works for me for dual stack.

**Comment by petrkr** [comment]
I can confirm it works like that (or I using it without that zero, so :::50002). Thanks. I thought it could be specified only one time those INI style variables

**Comment by cculianu** [comment]
Yeah some of these can be specified multiple times.. like `tcp=` and `ssl=`...
