### ISSUE TITLE
Could not create per-IP data in attachPerIPDataAndCheckLimits -- client may have already disconnected!

### ISSUE THREAD

**Issue by lvnilesh** [cculianu/Fulcrum#133]
Thanks for Fulcrum.

I have haproxy providing SSL support on port 50002 that points to fulcrum 1.7.0 without SSL running on tcp 50001

I see this message over and over in the logs. Wonder what may be causing this and how to avoid any related configuration mistake I may have made?

```
Sep 04 00:05:58 computername Fulcrum[640]: [2022-09-04 00:05:58.545] <TcpSrv 0.0.0.0:50001> Could not create per-IP data in attachPerIPDataAndCheckLimits -- client may have already disconnected!
```

**Comment by lvnilesh** [comment]
I see some reference to this topic in https://github.com/cculianu/Fulcrum/releases/tag/v1.5.4 

Let me check my logging level.

**Comment by cculianu** [comment]
So the error message itself may be safely ignored.  It's just more of a debug message, really.

I get lots of rapid conneciton-disconnection cycles too and always have. I figure it's just spammy clients that are misconfigured.. or something.  If a client rapidly connects then disconnects this message may pop up.  It's safe to ignore the message.  So long as the software you *actually* use on your end works ok -- then this may just be a symptom of some misconfigured clients or of some nefarious portscanners.

**Comment by lvnilesh** [comment]
Thanks. fulcrum is working correctly. Appreciate if you can please give me an example of a client that could be misconfigured.

**Comment by cculianu** [comment]
I think it's just portscanners.  People run programs that scan ports...
