### ISSUE TITLE
log trx anonymously

### ISSUE THREAD

**Issue by jpph** [cculianu/Fulcrum#140]
would it be possible to not log the exact trxid in fulcrum log file when broadcasting a trx?. Would be nice to have option to obscurate it... Or I think it should be by default anonymous, and an option would be needed to put it in the clear in the log file

**Comment by cculianu** [comment]
I added the `anon_logs` option yesterday to master. When I release, you can specify `anon_logs = true` in the conf file to not print this to  the log. Closing this issue as completed.
