### ISSUE TITLE
cashtoken related methods

### ISSUE THREAD

**Issue by mainnet-pat** [cculianu/Fulcrum#142]
Hey Calin, congrats with Nov. 15. feature freeze - it is cashtokens season now!

We would like to ask you about adding the cash token support in Fulcrum.

We can think of following new methods:

- listunspent extension with all relevant token utxo data - for token transfer transaction building
- get_balance extension for tokens - for UI presentation needs
- ...

We know we can live without these new methods by querying extra info (like raw transaction related to utxos) but it would lead to extra requests to Fulcrum server

**Comment by mainnet-pat** [comment]
Another reason for having token info in any form returned from listunspent is for utxo selection when building transactions.

Imagine you want to send plain bch, but taking some utxo from listunspent might lead to selecting a token utxo. so node will refuse to broadcast such a transaction, since there will be x tokens in inputs and 0 tokens in outputs.

**Comment by cculianu** [comment]
@jonas-lundqvist  had this to say on telegram:

> Jonas, [Nov 23, 2022 at 11:12:50 AM]:
> Should this be flagged in server.features?
>
> I  guess not all Electrum implementations will just tag along

He's right -- after we come up with the appropriate protocol extension -- it should be flagged in `server.features` so clients know what to expect (or not expect)... and can choose to not even connect to servers not offering the API extension.

**Comment by cculianu** [comment]
Ok, I hope 1.9.0's latest release handles this for now. Will close to keep issue count down but let me know if you want anything else later.
