### ISSUE TITLE
[Feature Request] Publish tagged releases to Dockerhub

### ISSUE THREAD

**Issue by openoms** [cculianu/Fulcrum#143]
Currently only the rolling `latest` tag is updated, but would be good to have tagged releases published again.
The last release on Dockerhub is v1.5.2 https://hub.docker.com/r/cculianu/fulcrum/tags.

**Comment by openoms** [comment]
@cculianu the latest release is not yet pushed to Dockerhub https://hub.docker.com/r/cculianu/fulcrum/tags yet. I wonder why https://github.com/cculianu/Fulcrum/blob/master/.github/workflows/publish.yml does not run on the creation of the release, could it be a permission issue?

**Comment by cculianu** [comment]
I just manually triggered it. I don't know how this github action stuff works. Maybe mainnet-pat can fix it... since he authored this mechanism.
