### ISSUE TITLE
Umbrel RPC local connection

### ISSUE THREAD

**Issue by santochibtc** [cculianu/Fulcrum#144]
Hi,
I want to run Fulcrum in a virtual machine connected to bitcoind from my Umbrel node via RPC local network.
./Fulcrum --datadir /home/user/fulcrum --bitcoind umbrel.local:8332 -u XX -p XX
I am getting this error:
_(Debug) on_connected 3
(Debug) on_connected 2
(Debug) on_connected 4
Got HTTP status 403 Forbidden; will log the rest of this HTTP response
403 (header): Date: Sun, 04 Dec 2022 18:03:02 GMT
Got HTTP status 403 Forbidden; will log the rest of this HTTP response
403 (header): Content-Length: 0
403 (header): Content-Type: text/html; charset=ISO-8859-1
Got unexpected content type: text/html; charset=ISO-8859-1; will log the rest of this HTTP response
403 (header): Date: Sun, 04 Dec 2022 18:03:02 GMT
403 (header): 
403 (header): Content-Length: 0
403 (content): 
403 (header): Content-Type: text/html; charset=ISO-8859-1
Got unexpected content type: text/html; charset=ISO-8859-1; will log the rest of this HTTP response
403 (header): 
403 (content):_ 
Error processing data coming in: Failed to parse Json from string: 
(Debug) do_disconnect (abort) 3

Do you know want I am doing wrong?
Thanks

**Comment by cculianu** [comment]
Looks like bitcoind is disallowing connections from your IP for some reason.  You may want to look into rpcallowip= config paran — you need to whitelist whatever subnet or ip that bitcoind sees fulcrum connection as coming from.

**Comment by santochibtc** [comment]
Thanks, it worked. I added the rpcallowip parameter to the ./umbrel/app-data/bitcoin/exports.sh file and restarted

**Comment by cculianu** [comment]
Yay! Glad it was that simple. :)
