### ISSUE TITLE
[Feature Request] Add PID support

### ISSUE THREAD

**Issue by melroy89** [cculianu/Fulcrum#147]
Just like `bitcoind` has an `-pid` option to specify a PID file. Like so: `-pid=/run/bitcoind/bitcoind.pid`

I would like to have a similar option (`-pid`) for Fulcrum, which allows me to easier manage the service in case of emergencies/failures. 

That would be great, thanks in advance!

Regards,
Melroy van den Berg

**Comment by cculianu** [comment]
Hmm. Any chance you can just parse the json from Fulcrum's "admin" port `getinfo` call?  It reports its PID in there..  On my system this is how I do it (my FulcrumAdmin port is port 8000 on localhost):

```bash
$ ./FulcrumAdmin -p 8000 getinfo | jq .pid
```

**Comment by danger89** [comment]
Nah. I'm now using the [Monit matching by process](https://mmonit.com/monit/documentation/monit.html#Process) instead of pidfile.

`check process Fulcrum matching "fulcrum"`

Which is good enough for now, I just think that a pidfile is maybe more robust. I could be wrong.

**Comment by melroy89** [comment]
Nice!
