### ISSUE TITLE
Feature: All configuration options as environment variables or CLI arguments

### ISSUE THREAD

**Issue by dorveille** [cculianu/Fulcrum#154]
Having all  configuration options available as environment variables or [CLI arguments](https://github.com/cculianu/Fulcrum/blob/master/doc/unix-man-page.md) would make it easier to deploy the `cculianu/fulcrum` docker image in to production. 

There are [well documented](https://github.com/cculianu/Fulcrum/blob/master/doc/fulcrum-example-config.conf) configuration options which are only available by specifying a configuration file. To use these requires maintaining a separate configuration file, as well as it requires having access to the filesystem before launching the container, which is not always possible or easy in cloud environments. A workaround might be to create a custom image based off `cculianu/fulcrum` and include a fulcrum.conf, but then this does not permit unique configuration values per environment.

Adding this support would make Fulcrum a first class citizen in the world of docker.

**Comment by cculianu** [comment]
Not a bad idea.

Hmm. Maybe a CLI arg can be used to specify that the args should come from the environment...?

**Comment by cculianu** [comment]
What about specifying the "conf" file as `/proc/self/environ` (linux only).  I can make it so the conf file parser knows how to read this file such that it translates the embedded `0x0` chars into -> `NL`

**Comment by cculianu** [comment]
Ok, this has been added. You can specify `_ENV_` as the config file name and it will read the environment instead (`/proc/self/environ` will also work).  This will appear in the next release of Fulcrum which I hope to get out soon (maybe this week).

Thanks for the suggestion! It was an easy and useful one!

**Comment by dorveille** [comment]
This is great, thanks for this! I'll test it out.
