### ISSUE TITLE
Anonymous Logs

### ISSUE THREAD

**Issue by apemithrandir** [cculianu/Fulcrum#156]
In ElectrumX it is possible to set `ANON_LOGS=1` in the config file. This allows you to run a server without logging any IP addresses or Bitcoin addresses.

Does such a feature exist on Fulcrum? If not, would it be possible to add it?

**Comment by cculianu** [comment]
This is not a bad suggestion. Would it be sufficient just to hide the IP addresses from external clients but otherwise show IPs in the logs for random stuff like peers?

**Comment by cculianu** [comment]
I guess we should also blank out things like txid's that may appear in the logs as well.

**Comment by cculianu** [comment]
Ok, this has been added in this commit: 2bea2e2a707e3f62066b24eb9204f75a6cc23470

I will go ahead and close this issue.  Expect the `anon_logs` option to appear in the next Fulcrum release (which I may put out soon).
