### ISSUE TITLE
Unknown output after extract "Fulcrum-1.9.1-x86_64-linux.tar.gz"

### ISSUE THREAD

**Issue by twofaktor** [cculianu/Fulcrum#167]
After extracting the latest compressed binaries I saw these output logs:

```
Fulcrum-1.9.1-x86_64-linux/
Fulcrum-1.9.1-x86_64-linux/man/
Fulcrum-1.9.1-x86_64-linux/FulcrumAdmin
Fulcrum-1.9.1-x86_64-linux/fulcrum-example-config.conf
Fulcrum-1.9.1-x86_64-linux/LICENSE.txt
Fulcrum-1.9.1-x86_64-linux/._Fulcrum
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.system.posix_acl_access'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.docker.grpcfuse.ownership'
Fulcrum-1.9.1-x86_64-linux/Fulcrum
Fulcrum-1.9.1-x86_64-linux/unix-man-page.md
Fulcrum-1.9.1-x86_64-linux/fulcrum-quick-config.conf
Fulcrum-1.9.1-x86_64-linux/man/Fulcrum.1
```

```
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.system.posix_acl_access'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.docker.grpcfuse.ownership'
```

![Captura2333242](https://user-images.githubusercontent.com/89636253/230792663-15ee325d-69eb-4779-9867-71593880aeb7.PNG)

What is this about? I didn't see it in previous versions

![Captura2352365](https://user-images.githubusercontent.com/89636253/230792851-2f682369-ac3e-4162-8acf-b632ee1fbdac.PNG)

I can see a new `"._Fulcrum"` hidden binary, what about it? could be the issue?

![Captura243756798](https://user-images.githubusercontent.com/89636253/230793112-2eb9d9be-f3a9-43a7-8bf1-edbf2546fc56.PNG)

**Comment by cculianu** [comment]
Hmm sorry about that. These are artifacts that macOS "invisibly" inserts sometimes into directories.  I tarred this up on macOS, not on Linux.  I'll re-tar on linux and re-sign the release so we can avoid these problems.

**Comment by cculianu** [comment]
Ok, I replaced the tarballs (tarred them on Linux this time) -- so no hidden magical macOS files are present. I re-signed them and re-uploaded them.

Please try the download again.

**Comment by twofaktor** [comment]
Solved! Thanks!
