### ISSUE TITLE
fulcrum.service: Main process exited, code=exited, status=1/FAILURE : Unable to open key file

### ISSUE THREAD

**Issue by Fort-Nakamoto** [cculianu/Fulcrum#171]
Hi,
I'm stuck trying to get latest Fulcrum version installed & running, appreciate any  help. :)

<img width="799" alt="Fulcrum_error" src="https://github.com/cculianu/Fulcrum/assets/123494093/f231d7e0-0328-43fa-80b6-5bd6025a6137">

Generated SSL key / cert with following command:
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem

fulcrum.conf file:
datadir = /home/fn/fulcrum_db
bitcoind = 127.0.0.1:8332
rpcuser = XXX
rpcpassword = XXX
ssl = 0.0.0.0:50002
cert = /home/fn/fulcrum/cert.pem
key = /home/fn/fulcrum/key.pem
peering = false
fast-sync = 5000

**Comment by Fort-Nakamoto** [comment]
Another clue: permission denied.

Fulcrum is running inside a container under Promox with Ubuntu Server installed as OS.

<img width="639" alt="Fulcrum_Permission_denied" src="https://github.com/cculianu/Fulcrum/assets/123494093/88ada0a2-f56f-45bf-89fa-4230e8195aad">

**Comment by cculianu** [comment]
By default the key.pem files are only readable by root... Maybe set permission on the file to be more permissive using chmod?

**Comment by Fort-Nakamoto** [comment]
Hi cculianu,
Thanks SO much for your support.
chmod resolved the permission issue, thank you!

But now there is a RPC connection refused error.  I double checked the bitcoin.conf file, which looks correctly configured using the py script rpcauth=fn:XXX.  Note Bitcoind is running in its own separate container.  Any ideas how to fix?    

<img width="809" alt="Fulcrum_running_RPC1_error" src="https://github.com/cculianu/Fulcrum/assets/123494093/0571430e-326f-41dd-9abd-a89b9f8a7371">
<img width="603" alt="Fulcrum_running_RPC2_error" src="https://github.com/cculianu/Fulcrum/assets/123494093/336bd523-72a4-4cb4-a133-0ab777d4e7a5">

**Comment by cculianu** [comment]
I dunno man I don't use containers I believe in the Unix process model. Sorry. 

I suggest ensuring the port is open across the 2 containers for connecting to RPC. Anyway it's beyond my capacity and interest to troubleshoot container issues. Good luck.
