### ISSUE TITLE
Help with mempool please

### ISSUE THREAD

**Issue by VegArchie** [cculianu/Fulcrum#176]
I am trying to get mempool (docker implementation) to connect with Fulcrum.  I am getting the following repeating errors:

`api_1  | Jun  4 00:20:27 [109] WARN: Exception in runMainUpdateLoop(). Retrying in 60 sec. Reason: ETIMEDOUT. Stack trace: Error: ETIMEDOUT
api_1  |     at Timeout._onTimeout (/backend/package/rpc-api/jsonrpc.js:66:23)
api_1  |     at listOnTimeout (node:internal/timers:559:17)
api_1  |     at processTimers (node:internal/timers:502:7)
api_1  | Jun  4 00:21:14 [109] ERR: Electrum error: {"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"172.27.0.1","port":50002}
api_1  | Jun  4 00:21:14 [109] ERR: Electrum error: {"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"172.27.0.1","port":50002}
api_1  | Jun  4 00:21:14 [109] INFO: Disconnected from Electrum Server at 172.27.0.1:50002
api_1  | Jun  4 00:22:30 [109] WARN: Exception in runMainUpdateLoop(). Retrying in 60 sec. Reason: connect ENETUNREACH 172.27.0.1:8332. Stack trace: Error: connect ENETUNREACH 172.27.0.1:8332
api_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
api_1  | Jun  4 00:23:25 [109] ERR: Electrum error: {"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"172.27.0.1","port":50002}
api_1  | Jun  4 00:23:25 [109] ERR: Electrum error: {"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"172.27.0.1","port":50002}
api_1  | Jun  4 00:23:25 [109] INFO: Disconnected from Electrum Server at 172.27.0.1:50002
api_1  | Jun  4 00:23:26 [109] INFO: Disconnected from Electrum Server at 172.27.0.1:50002
api_1  | Jun  4 00:23:26 [109] ERR: Electrum error: {"errno":-101,"code":"ENETUNREACH","syscall":"connect","address":"172.27.0.1","port":50002}
api_1  | Jun  4 00:23:26 [109] ERR: Electrum error: {"errno":-101,"code":"ENETUNREACH","syscall":"connect","address":"172.27.0.1","port":50002}`

Is there a config setting (for either mempool or fulcrum) I could have missed (I have tried several)?  FYI, Sparrow wallet connects on 50001 properly.

**Comment by VegArchie** [comment]
I tried the absolute IP address and I get different errors based on someones recommendation that it was a network/docker issue.

`api_1  | Jun  4 01:41:48 [109] WARN: Exception in runMainUpdateLoop(). Retrying in 60 sec. Reason: Invalid params, response status code: 403. Stack trace: Error: Invalid params, response status code: 403
api_1  |     at IncomingMessage.<anonymous> (/backend/package/rpc-api/jsonrpc.js:109:31)
api_1  |     at IncomingMessage.emit (node:events:539:35)
api_1  |     at endReadableNT (node:internal/streams/readable:1345:12)
api_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
api_1  | Jun  4 01:41:54 [109] INFO: Disconnected from Electrum Server at 192.168.0.123:50002
api_1  | Jun  4 01:41:54 [109] ERR: Electrum error: {}
api_1  | Jun  4 01:42:05 [109] ERR: Electrum error: {}
api_1  | Jun  4 01:42:05 [109] INFO: Disconnected from Electrum Server at 192.168.0.123:50002
api_1  | Jun  4 01:42:16 [109] ERR: Electrum error: {}
api_1  | Jun  4 01:42:16 [109] INFO: Disconnected from Electrum Server at 192.168.0.123:50002
api_1  | Jun  4 01:42:27 [109] INFO: Disconnected from Electrum Server at 192.168.0.123:50002
api_1  | Jun  4 01:42:27 [109] ERR: Electrum error: {}
api_1  | Jun  4 01:42:38 [109] INFO: Disconnected from Electrum Server at 192.168.0.123:50002
api_1  | Jun  4 01:42:38 [109] ERR: Electrum error: {}
api_1  | Jun  4 01:42:48 [109] WARN: Exception in runMainUpdateLoop(). Retrying in 60 sec. Reason: Invalid params, response status code: 403. Stack trace: Error: Invalid params, response status code: 403
`


Anyone know what these errors indicate? What parameters are invalid?

**Comment by VegArchie** [comment]
I tried without using docker and get a similar problem:

`Jun  4 12:28:13 [134278] DEBUG: Electrum attempting reconnect...
Jun  4 12:28:13 [134278] ERR: Electrum error: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":50002}
Jun  4 12:28:13 [134278] ERR: Electrum error: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":50002}
Jun  4 12:28:13 [134278] INFO: Disconnected from Electrum Server at 127.0.0.1:50002
`

**Comment by VegArchie** [comment]
eventually got it working through brute force trial and error. Had to use absolute IP address of the machine

**Comment by cculianu** [comment]
Ah I was going to say this is just some network setup issue outside of Fulcrum. Glad you figured it out!

**Comment by alexdatur** [comment]
Please help i have same erro in docker mempool + citcoin core.
my example compose:
api:
    environment:
      MEMPOOL_BACKEND: "none"
      BITCOIN_NETWORK: "mainnet"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
      CORE_RPC_HOST: "172.27.0.2"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "test"
      CORE_RPC_PASSWORD: "test"
      CORE_RPC_TIMEOUT: 60000
    image: mempool/backend:latest
    networks:
            mempool_default:
                ipv4_address: 172.27.0.3
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache

 

  bitcoin:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoin
    volumes:
      - ./bitcoin-data:/bitcoin/.bitcoin
    environment:
      BITCOIN_EXTRA_ARGS: |
        server=1
        txindex=1
        rpcuser=test
        rpcpassword=test
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
    ports:
      - "8332:8332" # RPC
      - "8333:8333" # P2P
      - "28332:28332" # ZMQ
      - "28333:28333" # ZMQ
    networks:
            mempool_default:
                ipv4_address: 172.27.0.2
    restart: unless-stopped
    
    and have in api container error:
    Dec 31 23:15:35 [142] WARN: Exception in runMainUpdateLoop() (count: 133). Retrying in 1 sec. Reason: connect ECONNREFUSED 172.27.0.2:8332. Stack trace: Error: connect ECONNREFUSED 172.27.0.2:8332
    
    
    But containers in same network, i cant understaand. Can somebody help?

**Comment by 0-100eth** [comment]
It usually boils down to one (or both) of the following issues when you see ECONNREFUSED with Bitcoin Core and Mempool backend in Docker:
	1.	Bitcoin Core is not actually listening on 0.0.0.0
	2.	Bitcoin Core does not allow RPC connections from the Docker network

Below are some steps and tips to help you troubleshoot and fix it.

1. Make sure Bitcoin Core is listening on 0.0.0.0

By default, Bitcoin Core may only listen on 127.0.0.1 for RPC. That means other containers (on a different internal IP) cannot connect. You need to tell Bitcoin Core to listen on all interfaces so that the Mempool container can access port 8332 internally.

In your docker-compose.yml, add these lines to Bitcoin Core’s BITCOIN_EXTRA_ARGS:

bitcoin:
  image: ruimarinho/bitcoin-core:latest
  container_name: bitcoin
  volumes:
    - ./bitcoin-data:/bitcoin/.bitcoin
  environment:
    BITCOIN_EXTRA_ARGS: |
      server=1
      txindex=1
      rpcuser=test
      rpcpassword=test
      # Add these:
      rpcbind=0.0.0.0
      rpcallowip=0.0.0.0/0
      zmqpubrawblock=tcp://0.0.0.0:28332
      zmqpubrawtx=tcp://0.0.0.0:28333
  ports:
    - "8332:8332"  # RPC
    - "8333:8333"  # P2P
    - "28332:28332" # ZMQ
    - "28333:28333" # ZMQ
  networks:
    mempool_default:
      ipv4_address: 172.27.0.2
  restart: unless-stopped

The key directives here are:
	•	rpcbind=0.0.0.0
	•	rpcallowip=0.0.0.0/0

This ensures the Bitcoin container is actually listening for RPC on the container’s IP (172.27.0.2) and allowing connections from the Docker network.

(You can narrow rpcallowip down to just your Docker subnet, e.g. 172.27.0.0/16, if you want a tighter firewall rule. The “all IP” example just makes sure it’s open for testing purposes.)

2. Verify the Docker network configuration

You’ve set static IPs in your docker-compose.yml:

networks:
  mempool_default:
    ipam:
      config:
        - subnet: 172.27.0.0/16

For this to work properly, make sure:
	•	You’ve defined the ipam section as above for the mempool_default network.
	•	Both containers (bitcoin and api) are actually attached to mempool_default using that subnet.

It might look like this in a simplified form:

version: '3.8'
services:
  bitcoin:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoin
    networks:
      mempool_default:
        ipv4_address: 172.27.0.2
    # ...

  api:
    image: mempool/backend:latest
    networks:
      mempool_default:
        ipv4_address: 172.27.0.3
    # ...
  
networks:
  mempool_default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16

If you do not explicitly declare the IPAM subnet block, Docker can override or ignore the IP addresses you specify, which might lead to containers not actually getting 172.27.0.x.

Also, confirm that your MEMPOOL_BACKEND environment variables match those IPs:

MEMPOOL_BACKEND: "none"
BITCOIN_NETWORK: "mainnet"
CORE_RPC_HOST: "172.27.0.2"    # This must match the Bitcoin container IP
CORE_RPC_PORT: "8332"
CORE_RPC_USERNAME: "test"
CORE_RPC_PASSWORD: "test"

3. Try using container names instead of fixed IP

A simpler approach (and often more “Docker-friendly”) is to rely on Docker’s internal DNS. You can do:

services:
  bitcoin:
    container_name: bitcoin
    # ...

  api:
    environment:
      CORE_RPC_HOST: "bitcoin"  # Use container name, not IP
    # ...

That way, Docker will automatically resolve bitcoin to the correct IP on the internal network. You’d still need the rpcbind and rpcallowip settings in your Bitcoin config, but it removes the need for static IP addresses.

4. Test connectivity inside the containers

When you have everything up and running, you can exec into the API container and try to ping or curl the Bitcoin container:

docker compose exec api ping 172.27.0.2
docker compose exec api curl 172.27.0.2:8332

(or if using container names)

docker compose exec api ping bitcoin
docker compose exec api curl bitcoin:8332

If that succeeds, you’ll see that the network and ports are reachable. If it fails, check the logs of both containers and the Docker network configuration.

Summary
	1.	Allow external RPC in the Bitcoin container: rpcbind=0.0.0.0, rpcallowip=0.0.0.0/0.
	2.	Double-check your Docker network is properly configured (static IP + IPAM if you need it).
	3.	Optionally switch to using Docker’s container name (CORE_RPC_HOST=bitcoin), which often simplifies networking.
	4.	Verify connectivity with docker compose exec commands to confirm that the port is open.

Most often, setting rpcbind + rpcallowip and ensuring the containers truly share a network with no firewall in between fixes the problem.

**Comment by alexdatur** [comment]
Thanx, use this config, but stuck at same.:
version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - "127.0.0.1:3006:8080"
    networks:
      mempool_default:
        ipv4_address: 172.27.0.5

  api:
    environment:
      MEMPOOL_BACKEND: "none"
      BITCOIN_NETWORK: "mainnet"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
      CORE_RPC_HOST: "172.27.0.2"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "test"
      CORE_RPC_PASSWORD: "test"
      CORE_RPC_TIMEOUT: 60000
    image: mempool/backend:latest
    networks:
      mempool_default:
        ipv4_address: 172.27.0.3
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache

  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.21
    networks:
      mempool_default:
        ipv4_address: 172.27.0.4
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql

  bitcoin:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoin
    volumes:
      - ./bitcoin-data:/bitcoin/.bitcoin
    environment:
      BITCOIN_EXTRA_ARGS: |
        server=1
        txindex=1
        rpcuser=test
        rpcpassword=test
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
        rpcallowip=::/0
        rpcbind=0.0.0.0
        rpcport=8332
    ports:
      - "8332:8332"
      - "8333:8333" # P2P
      - "28332:28332" # ZMQ
      - "28333:28333" # ZMQ
    networks:
      mempool_default:
        ipv4_address: 172.27.0.2
    restart: unless-stopped

networks:
  mempool_default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.27.0.0/16"
        
        
       recreate containers, but:
       wait-for-it.sh: waiting 720 seconds for db:3306

wait-for-it.sh: db:3306 is available after 0 seconds

Jan  1 09:56:16 [141] NOTICE: Starting Mempool Server... (6177899)

Jan  1 09:56:16 [141] INFO: Database connection established.

Jan  1 09:56:17 [141] INFO: Starting statistics service

Jan  1 09:56:17 [141] ERR: Cannot get fetch orphaned blocks. Reason: connect ECONNREFUSED 172.27.0.2:8332

Jan  1 09:56:17 [141] NOTICE: Mempool Server is running on port 8999

Jan  1 09:56:20 [141] INFO: Latest BTC fiat averaged price: {"time":1735725380,"USD":93218,"EUR":90096,"GBP":74501,"CAD":133825,"CHF":84111,"AUD":151073,"JPY":14673000}

Jan  1 09:56:21 [141] WARN: Exception in runMainUpdateLoop() (count: 5). Retrying in 1 sec. Reason: connect ECONNREFUSED 172.27.0.2:8332. Stack trace: Error: connect ECONNREFUSED 172.27.0.2:8332

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)

Jan  1 09:56:22 [141] NOTICE: [Mining] Inserted 8 daily historical prices into the db

Jan  1 09:56:22 [141] WARN: Exception in runMainUpdateLoop() (count: 6). Retrying in 1 sec. Reason: connect ECONNREFUSED 172.27.0.2:8332. Stack trace: Error: connect ECONNREFUSED 172.27.0.2:8332

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)

Jan  1 09:56:23 [141] WARN: Exception in runMainUpdateLoop() (count: 7). Retrying in 1 sec. Reason: connect ECONNREFUSED 172.27.0.2:8332. Stack trace: Error: connect ECONNREFUSED 172.27.0.2:8332

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
    
    my red eyes slowly diyng.. cause i cant understand whats wrong(
