### ISSUE TITLE
"Limit" option for get_history call as per Electrum Protocol 2.0

### ISSUE THREAD

**Issue by kzKallisti** [cculianu/Fulcrum#180]

**Comment by cculianu** [comment]
Reference: https://github.com/spesmilo/electrumx/pull/90/files#diff-ffa7e37c618564f8c58d9072b5ef234e6e9b2cdf1d71d16be7dc356146cb475fR327

I will probably initially do this as optional second and third args: `from_height` and `to_height` (see above link for description).  Is that acceptable to you @kzKallisti ?

**Comment by cculianu** [comment]
Ok, this has been implemented on master.  To test, one must either wait for me to do a release or compile from master. Here are the API docs: https://electrum-cash-protocol.readthedocs.io/en/latest/protocol-methods.html#blockchain.scripthash.get_history
