### ISSUE TITLE
Make-your-own passthrough

### ISSUE THREAD

**Issue by imaginaryusername** [cculianu/Fulcrum#188]
A feature where the operator can specify specific command(s) to pass through from the underlying node (say, `getdsproofscore`) in Fulcrum's config. Once enabled, wallets can then request from Fulcrum and get whatever the node replies through Fulcrum. 

A number of niche uses from the full node like doublespend proof, gettx verbosity and perhaps even getblocktemplate have their niche users who want to unify a pull from a single interface to Fulcrum, instead of creating and managing a separate interface to the full node itself. Some of these are complex (dsproof) or too hefty for the general network (verbosity, gbt) to be cached, indexed and have a specific facility at Fulcrum itself enabled by default. However many of these users are perfectly fine with running their own private nodes and would love to pass RPC commands through Fulcrum.

**Comment by cculianu** [comment]
Ok, I just implemented this on master via commit 1b8ce7feb084767205bab3b891c0b7b111757967.  Closing. Will be a part of the upcoming Fulcrum release.
