### ISSUE TITLE
Fulcrum.service running but connection refused

### ISSUE THREAD

**Issue by shishna** [cculianu/Fulcrum#189]
fulcrum.service - Fulcrum
     Loaded: loaded (/etc/systemd/system/fulcrum.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-07-19 13:17:54 BST; 5min ago
   Main PID: 7464 (Fulcrum)
      Tasks: 23 (limit: 9324)
     Memory: 9.8M
        CPU: 162ms
     CGroup: /system.slice/fulcrum.service
             └─7464 /home/lenovo/fulcrum/Fulcrum /home/lenovo/fulcrum/fulcrum.conf

Jul 19 13:22:44 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:44.492] <BitcoinD.3> TCP BitcoinD.3 (id: 4): error 0 (Connection refused)
Jul 19 13:22:44 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:44.496] <BitcoinD.2> TCP BitcoinD.2 (id: 3): error 0 (Connection refused)
Jul 19 13:22:44 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:44.500] <Controller> Waiting for bitcoind...
Jul 19 13:22:49 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:49.491] <BitcoinD.3> TCP BitcoinD.3 (id: 4): error 0 (Connection refused)
Jul 19 13:22:49 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:49.491] <BitcoinD.2> TCP BitcoinD.2 (id: 3): error 0 (Connection refused)
Jul 19 13:22:49 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:49.495] <BitcoinD.1> TCP BitcoinD.1 (id: 2): error 0 (Connection refused)
Jul 19 13:22:54 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:54.491] <BitcoinD.2> TCP BitcoinD.2 (id: 3): error 0 (Connection refused)
Jul 19 13:22:54 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:54.494] <BitcoinD.3> TCP BitcoinD.3 (id: 4): error 0 (Connection refused)
Jul 19 13:22:54 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:54.495] <BitcoinD.1> TCP BitcoinD.1 (id: 2): error 0 (Connection refused)
Jul 19 13:22:54 ideapad-laptop Fulcrum[7464]: [2023-07-19 13:22:54.499] <Controller> Waiting for bitcoind...

**Comment by shishna** [comment]
In case it matters. I was following ministry of nodes guide.

**Comment by EchterAgo** [comment]
Is your bitcoind running properly?

**Comment by EchterAgo** [comment]
What `bitcoind` setting do you have in the configuration file and is that port actually open? The message says it is closed.

You can check using `ss -tulpn` for listeners.

**Comment by EchterAgo** [comment]
There is no port 8332 open. You seem to not have set up bitcoind RPC correctly. Also the listeners there are from bitcoin-qt, not bitcoind, are you sure that is what you want?

**Comment by shishna** [comment]
Not sure to be honest. I dont know what the difference is. What do you recommend ? Do I have to reinstall everything again ?

**Comment by EchterAgo** [comment]
The default RPC port is port 8332, but what you end up using depends on your configuration. But yes, Fulcrum needs an RPC port to connect to and yours is not open. If you can't use the `bitcoin-cli` tool with either `bitcoin-qt` or `bitcoind` then your RPC is not set up right. In any case, this is not an issue with Fulcrum.

**Comment by shishna** [comment]
Yeah I tried using bitcoin-cli and command is not found. So can I go back and setup RPC correctly now or too late ?

**Comment by EchterAgo** [comment]
From the Fulcrum side everything should be fine once you get an RPC port up and running. You should consult the documentation / help forums of the node software you are using on how to get RPC working.
