### ISSUE TITLE
Pruning node after full sync

### ISSUE THREAD

**Issue by Ryba1986** [cculianu/Fulcrum#190]
Can i enable pruning after full sync?

**Comment by cculianu** [comment]
No, don’t do that. I think fulcrum refuses to run if you do that. The design of the electrum protocol assumes any txn from the blockchain can be retrieved by clients at any time. Even if fulcrum allowed that, it would lead to your server basically being a very bad server for clients.

**Comment by Ryba1986** [comment]
Ok thanks for the explanation.
