### ISSUE TITLE
consider: get block header by hash

### ISSUE THREAD

**Issue by monsterbitar** [cculianu/Fulcrum#191]
It would be useful in some cases to be able to request a block header from a block header hash.

I propose a method that takes a block header hash as input, and provides a dictionary of the block header hex and the respective block height.

If no such header is available, instead return an error string indicating that the header was not found in the current chain.

**Comment by cculianu** [comment]
Ok, added in #211. Will merge that and 210 later today/tomorrow.

**Comment by cculianu** [comment]
Implemented in #211
