### ISSUE TITLE
Output Unknown logs --> tar: Ignoring unknown extended header keyword....

### ISSUE THREAD

**Issue by twofaktor** [cculianu/Fulcrum#198]
After extracting the pre-compiled binaries for Linux x86_64 ( Fulcrum-1.9.2-x86_64-linux.tar.gz ) the decompressor showed me the next output unknown logs:

```
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.system.posix_acl_access
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.docker.grpcfuse.ownership
```

![imagen](https://github.com/cculianu/Fulcrum/assets/89636253/0f311bce-6fe7-46d7-a395-3ed7b3f144fc)

Is this a known bug? or can we ignore it? 

thanks

**Comment by twofaktor** [comment]
Ok, I found a before issue with the same problem: https://github.com/cculianu/Fulcrum/issues/167

**Comment by cculianu** [comment]
This is just some stuff that comes in because I use macOS with an xattr-capable filesystem. macOS loves loves LOVES to add additional xattrs and I guess they end up in the tarball.

Can be safely ignored. Those attrs are mostly meaningless.
