### ISSUE TITLE
Verifying the Release

### ISSUE THREAD

**Issue by TinF0ilHat1** [cculianu/Fulcrum#204]
I was thinking: what is the purpose of releasing a `.asc` for each file plus the corresponding hash `.sha256.sum`?
Once i `gpg --verify` the `.asc` against the corresponding file there is no point  checking if the hash matches the one you wrote. I can already be sure that the file is legit since i already got a `Good signature from "Calin Culianu (NilacTheGrim) <calin.culianu@gmail.com>"`

I would have expected you to write a manifest.txt with all the hashes and then sign ( attached or not) it. 
You can reach a good community here, we are big fans of your project- hope to see you there
https://t.me/SovereignBitcoiner

**Comment by cculianu** [comment]
> I was thinking: what is the purpose of releasing a .asc for each file plus the corresponding hash .sha256.sum?

I don't know. It's what people in the crypto world seem to like, for some reason.

> I would have expected you to write a manifest.txt with all the hashes and then sign ( attached or not) it.

How is that any different than what happens now?

**Comment by cculianu** [comment]
Oh wait -- you're probably sight. The shasum files are useless.  I should be signing everything. Will-do next release if I remember.

**Comment by cculianu** [comment]
Yeah you're 100% right. You ever do something.. not thinking about it.. and then someone points it out to you that what you are doing makes no sense. And then you wonder all along how you never once stopped to think about it and how yes, what you are doing makes no sense.

I feel that way now. 100% I will do this next release.. or maybe even now.

**Comment by cculianu** [comment]
Ok, I generated a *single* sha256sum file and signed that. I am including both the bare .txt file and the signed .asc file (which embeds the .txt within itself for redundancy, ha!).

Is that ok? Or should I just delete the .txt file and leave only the .asc?

**Comment by cculianu** [comment]
Yeah good point. I'll nuke the .txt and leave the .asc. I forgot about the gpg warning... true.
