### ISSUE TITLE
Docker Image for v1.9.3 missing

### ISSUE THREAD

**Issue by petzsch** [cculianu/Fulcrum#205]
Can't find it here: https://hub.docker.com/r/cculianu/fulcrum/tags

Would be nice for updating existing deployments without building my own docker images.

**Comment by cculianu** [comment]
Oops. My bad. I forgot to trigger the publish action. It's running now. I think it should push out when finished... Closing issue but please re-open if it fails or is broken.

**Comment by cculianu** [comment]
Yep. It's there now. Sorry my bad.
