### ISSUE TITLE
--fast-sync option issue

### ISSUE THREAD

**Issue by twofaktor** [cculianu/Fulcrum#208]
After the initial sync, I found this error appeared me when I restart Fulcrum:

```
Started Fulcrum.
Oct 31 08:46:33 minibolt Fulcrum[3602272]: [2023-10-31 08:46:33.999] fast-sync: Specified value (4096000000 bytes) is too large to fit in available system memory (limit is: 3903692800 bytes)
Oct 31 08:46:33 minibolt Fulcrum[3602272]: [2023-10-31 08:46:33.999] Use the -h option to show help.
Oct 31 08:46:34 minibolt systemd[1]: fulcrum.service: Main process exited, code=exited, status=1/FAILURE
```

According to these lines, this requirement should not exist outside of the initial sync:
https://github.com/cculianu/Fulcrum/blob/master/doc/fulcrum-example-config.conf#L706-L707

This is solved by commenting on that line in the configuration file, but I think it should not be the expected behavior according to the parameter comment

Is it a known issue?

**Comment by cculianu** [comment]
Oh wait you know what? I'm wrong 100%. I just checked the code.  You are right in that this option really has no effect on the first synch at startup. You were 100% correct in your initial bug report.  The app ignores this options on the first synch at startup typically.  Only on the actual initial synch does it use this option.

My bad -- I just got home and opened up the code.

Yeah so what's going on is the arg parser has no way of knowing whether the `--fast-sync` option is legit going to be applied or not (that decisions happens later), hit it DOES enforce the memory checking thing.

Hmm.  

This def is a misbehavior of the app .. not sure if I would classify it as a bug per se.  

Sorry for the false explanation before. I mis-rembered how this worked and who was responsible for what I had to check the code again (I implemented this like ~1.5 years ago, heh).

**Comment by cculianu** [comment]
You know what? I'll move the enforcement to be a non-fatal error to later in the pipeline.  This way you can leave your config file undisturbed.  Will fix this.

**Comment by cculianu** [comment]
Ok, I pushed [2c1b263](https://github.com/cculianu/Fulcrum/commit/2c1b26334ab8186bdaa6450237426d3d1759f9a6) addresses the issue you experienced.  Are you set-up to re-build Fulcrum and check that it solves the situation you encountered?

By the way thanks for the bug report. If this happened to you, and it annoyed you enough to report it -- chances are it annoyed others too in the past or will in the future!

Closing for now.. report back if it still happens.

Thanks again!

**Comment by twofaktor** [comment]
Uhm...I don't compile from source code (there are no easy instructions to get this on the README 😜) and I can see you didn't change the precompiled binaries, should I wait for the next 1.9.6 release?

Thanks for your fast response ❤️

**Comment by cculianu** [comment]
Hmm. I could just post up some binaries here in this thread.  What platform? x86_64 linux? arm64 linux?

**Comment by cculianu** [comment]
Oh yeah what happened is I am using a new docker image to build it. Yeah, I think that may have broken for some people. It needs a newer glibc, etc.  Yes, open a new issue.

I'll post both binaries in here... and sign them. Off latest master.

**Comment by twofaktor** [comment]
> Oh yeah what happened is I am using a new docker image to build it. Yeah, I think that may have broken for some people. It needs a newer glibc, etc. Yes, open a new issue.

New issue opened: https://github.com/cculianu/Fulcrum/issues/209

**Comment by cculianu** [comment]
x86_64 linux:

[Fulcrum-1.9.5-2c1b263-x86_64-linux.tar.gz](https://github.com/cculianu/Fulcrum/files/13268907/Fulcrum-1.9.5-2c1b263-x86_64-linux.tar.gz)

signature for above (signed the binary itself).. github won't let me attach it for some reason so i'm pasting it here:

```
-----BEGIN PGP SIGNATURE-----

iHUEABEIAB0WIQTUZRNfl9AEfhjpncMhgQpUIDHALAUCZUkGpgAKCRAhgQpUIDHA
LJLFAP4z55tHiasgGNCJMmzOgtYO8WbhH0E4uJV41B+HW8SuCgEAnkJ3Dog7XtJK
tqxQRUlV9x/tjWwu6iemXFBTHZNSyLs=
=SUcw
-----END PGP SIGNATURE-----
```

**Comment by twofaktor** [comment]
> x86_64 linux:
> 
> [Fulcrum-1.9.5-2c1b263-x86_64-linux.tar.gz](https://github.com/cculianu/Fulcrum/files/13268907/Fulcrum-1.9.5-2c1b263-x86_64-linux.tar.gz)
> 
> signature for above (signed the binary itself).. github won't let me attach it for some reason so i'm pasting it here:
> 
> ```
> -----BEGIN PGP SIGNATURE-----
> 
> iHUEABEIAB0WIQTUZRNfl9AEfhjpncMhgQpUIDHALAUCZUkGpgAKCRAhgQpUIDHA
> LJLFAP4z55tHiasgGNCJMmzOgtYO8WbhH0E4uJV41B+HW8SuCgEAnkJ3Dog7XtJK
> tqxQRUlV9x/tjWwu6iemXFBTHZNSyLs=
> =SUcw
> -----END PGP SIGNATURE-----
> ```

Ok, solved!! thanks!! 🔥

![imagen](https://github.com/cculianu/Fulcrum/assets/89636253/d9d92aae-31e9-446c-b234-ce1d5eabfe3a)
![imagen](https://github.com/cculianu/Fulcrum/assets/89636253/60138496-b6ca-4a34-8c67-0e2d2154f077)

Anyway, will be this fix included in the next v1.9.6 release, right?

**Comment by cculianu** [comment]
> Anyway, will be this fix included in the next v1.9.6 release, right?

Yeah, for sure.

**Comment by cculianu** [comment]
Hey that's pretty cool console highlighting you got going on -- off-topic but: how do you do that?

**Comment by cculianu** [comment]
Ah never used MobaXterm. Pretty cool. I'll check it out.
