### ISSUE TITLE
Precompiled arm64 binary doesn't work since v1.9.2 on Raspberry OS arm64 (bullseye) - Debian 11 based

### ISSUE THREAD

**Issue by twofaktor** [cculianu/Fulcrum#209]
Since 1.9.2, I can't use Fulcrum precompiled arm64 binary on Raspberry OS arm64 (bullseye) - Debian 11 based, it shows me this error:

```
Fulcrum: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by Fulcrum)
Fulcrum: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by Fulcrum)
Fulcrum: /lib/aarch64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by Fulcrum)
Fulcrum: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by Fulcrum)
Fulcrum: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by Fulcrum)
Fulcrum: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by Fulcrum)
```

I think since that release, you updated dependencies and your precompiled binary is no longer compatible with this OS version, I will need from now on I will have to build it from the source code? Is there any other solution?

Comment related: https://github.com/cculianu/Fulcrum/issues/208#issuecomment-1795038768
Answer related: https://github.com/cculianu/Fulcrum/issues/208#issuecomment-1795048331

**Comment by cculianu** [comment]
Yess.. hmm. I updated the system to use a docker base image of Ubuntu 22.04.. which might rely on a glibc that is too new for some systems.

I used to build it on a physical RPi itself running Ubuntu 20 or 21 or something.. let me see if I can somehow use a docker image of Ubuntu 21 or 22... hmm.

**Comment by cculianu** [comment]
Hey man so I pushed a commit that adds a docker builder for arm64 using Ubuntu 20. This hopefully uses an old enough glibc that it runs on that system for you.  Let me know if this works for you and if it does I can update the release binary.

Note this is the raw binary, gzipped.. no tarball.

[Fulcrum.gz](https://github.com/cculianu/Fulcrum/files/13272032/Fulcrum.gz)

```
-----BEGIN PGP SIGNATURE-----

iHUEABEIAB0WIQTUZRNfl9AEfhjpncMhgQpUIDHALAUCZUlIQAAKCRAhgQpUIDHA
LBDkAQD2bqvKRRJh/eW9SIKDHg3uoyXK7w9JM5SAE79VdpZB9QEAlVOJxU6htTEM
NLslCQ8yywF2zy1Tad+hOlapVX4wDXk=
=LIuo
-----END PGP SIGNATURE-----
```

**Comment by twofaktor** [comment]
Hey! Good! Thanks!

Could you add FulcrumAdmin binary? I usually to use this tool also, in [my guide](https://v2.minibolt.info/bitcoin/bitcoin/electrum-server#admin-script-fulcrumadmin) currently 😁

**Comment by cculianu** [comment]
It's not a binary it's just a python script (text file). You can copy it from the current release...

**Comment by twofaktor** [comment]
> It's not a binary it's just a python script (text file). You can copy it from the current release...

Hey man! I'm not a programmer nor an expert, so I don't have enough knowledge to understand you easily, I'm sorry 🙏

I thought you would provide me something like this: https://github.com/cculianu/Fulcrum/files/13268907/Fulcrum-1.9.5-2c1b263-x86_64-linux.tar.gz for arm64, and be able to try it (I know how to do this)

Could you explain to me step by step what you want me to do? 

Thanks and sorry again

**Comment by cculianu** [comment]
It's ok.  Ok so the above `Fulcrum.gz` is literally the binary for the `Fulcrum` app.  Just do `gunzip Fulcrum.gz` and you will get `Fulcrum`, which can be run.  I didn't go to the trouble to do a full preparation of the whole tarball since .. that takes time to prepare manually liek this as a one-off.  Anyway... downlaod the above `Fulcrum.gz`, `gunzip` it, and make sure it's runnable via `chmod 755 Fulcrum`.  You can run it.

if you require the `FulcrumAdmin` script -- that's just a text file (it's basically a python script which is always a text file).  You can grab that from the x86 release or the arm64 release or whatever.

I hope that is clear?  or?

I just need confirmation that binary I linked above *works* on your system. If it does I can go ahead and update the current `arm64` release to include a binary like that -- built with Ubuntu 20 (rather than Ubuntu 22).

Thanks!

**Comment by cculianu** [comment]
Awesome! yes!  I will replace the 1.9.5 binary sometime today..

**Comment by cculianu** [comment]
Ok, I updated the release binary for arm64 to use this build method (Ubuntu 20).  Note it's not exactly the same commit as the other binaries (it's vs current master, basically), but that's ok.

Closing issue.

**Comment by twofaktor** [comment]
Ok, tested it again, and working fine! ✅ 

Thanks!
