### ISSUE TITLE
Checksum failure 

### ISSUE THREAD

**Issue by oPFGKk9gtuw8nuHkzrQn** [cculianu/Fulcrum#215]
Trying to update from 1.9.6 to 1.9.7.

![IMG_20231123_165232_650](https://github.com/cculianu/Fulcrum/assets/121948323/f2c276ec-2b91-4761-8257-8bb59f29e8bd)

There is a checksum error.
The Fulcrum-1.9.7-sha256sums.txt doesn't match the file Fulcrum-1.9.7-arm64-linux.tar.gz

**Comment by openoms** [comment]
That is likely a mistake, the hash of `Fulcrum-1.9.7-sha256sums.txt` shouldn't be included in the file itself.

Otherwise the binary hashes and the PGP signature matches so the Fulcrum binary is correctly signed by @cculianu

**Comment by cculianu** [comment]
Doh. LOL.  Yeah probably because I did it this time in the same directory e.g. `sha256sum Fulcrum* > Fulcrum-1.9.7-shasums.txt`.  Sorry about that.

Ok fixed and updated the release.
