### ISSUE TITLE
Wallets cannot retrieve transactions

### ISSUE THREAD

**Issue by cairesantos** [cculianu/Fulcrum#224]
I have just setup Fulcrum 1.9.7 on MacOS BigSur and it is running fine apparently. I tried to connect with both wallets Sparrow and Electrum, but neither of them could retrieve transactions from the server.

I made some ss from the terminal and sparrow (as ithe GUI gives more info than electrum).

Any help would be appreciated.

SS below shows Sparrow connected to the wallet
<img width="750" alt="Screenshot 2024-01-06 at 00 50 46" src="https://github.com/cculianu/Fulcrum/assets/154569451/01e862e0-6f3f-4df3-b6e6-64eac272b47e">

SS below shows Sparrow processing errors when reloading the wallet
<img width="847" alt="Screenshot 2024-01-06 at 00 52 47" src="https://github.com/cculianu/Fulcrum/assets/154569451/e0be5703-f77c-47f1-b0f8-18ce5778f1f7">

SS below shows my other laptop successfully connected to Fulcrum
<img width="773" alt="Screen Shot 2024-01-06 at 00 55 14 1" src="https://github.com/cculianu/Fulcrum/assets/154569451/9ddeaf0e-d851-4207-9c39-0726381b8eb3">

**Comment by cculianu** [comment]
Make sure you run your Bitcoin node with `-txindex=1`.  If you don't, you won't be able to retrieve txns.

**Comment by cairesantos** [comment]
I have that on my bitcoin config file, but apparently it did not process it?

<img width="430" alt="Screen Shot 2024-01-06 at 08 31 59" src="https://github.com/cculianu/Fulcrum/assets/154569451/51f637a3-7b3c-49d3-ae75-bd859f57e7b0">

**Comment by cculianu** [comment]
Don't worry about obfuscation key. That's some old option to get virus scanners to leave bitcoin alone.

Not sure what is going on with your  setup and why it can't retrieve certain txns.  Maybe Sparrow cached them from a previous mempool.. but since your node just came up.. they aren't in your node's mempool?  Are these txns all unconfirmed?

**Comment by cairesantos** [comment]
I figured it out. Actually, it fixed by itself!

After fuclrum indexed the whole database, I set txindex=1 on bitcoin core and brought it online again. I thought I hat txindex was just an instruction to allow the usage of indexation within bitcoin core. However, when I opened debug file i saw core actually indexing the whole blockchain. After it finished, the wallets started to load the transactions just fine. 

If i may ask another quick question. How to i shut down fulcrum safely? I did not set the admin port and now I couldn’t do it via terminal. When I open terminal and run the command, it actually tries to start fulcrum again and fails, of course. Is there a why to make fulcrum just reload de conf file, or is there a way to shut it down safely without the admin CLI?

**Comment by cculianu** [comment]
How's it running? You can hit CTRL-C or send it: SIGINT or SIGTERM and it will shut down gracefully.

**Comment by cairesantos** [comment]
It’s running on MacOS BigSur via CLI. 

I hit `./Fulcrum Fulcrum.conf ` on Terminal. 

On the same terminal window running Fulcrum, can I type SIGTERM + Enter?

**Comment by cculianu** [comment]
Just hit Ctrl-C
