### ISSUE TITLE
Bug: Some Timestamps are wrong

### ISSUE THREAD

**Issue by andreasgriffin** [cculianu/Fulcrum#233]
Some of the timestamps are wrong. 
Using bdkpython 0.31.0 I query my fulcrum mainnet bitcoin server with
```python
import bdkpython as bdk 
import datetime

network = bdk.Network.BITCOIN
if network == bdk.Network.BITCOIN:
    blockchain_config = bdk.BlockchainConfig.ELECTRUM(
        bdk.ElectrumConfig(
            "my_fulcrum_server:50001", 
            None,
                10,
            10,
            100,
            False
        )
    ) 


blockchain = bdk.Blockchain(blockchain_config)


mnemonic = bdk.Mnemonic.from_string('bacon '*24)
print(mnemonic.as_string())


descriptor = bdk.Descriptor.new_bip84(
            secret_key=bdk.DescriptorSecretKey(network, mnemonic, ''),
             keychain=bdk.KeychainKind.EXTERNAL,
             network=network,
)


change_descriptor = bdk.Descriptor.new_bip84(
            secret_key=bdk.DescriptorSecretKey(network, mnemonic, ''),
             keychain=bdk.KeychainKind.INTERNAL,
             network=network,
)

 
print(f'xpub {descriptor.as_string()}')



wallet = bdk.Wallet(
             descriptor=descriptor,
             change_descriptor=change_descriptor,
             network=network,
             database_config=bdk.DatabaseConfig.MEMORY(),
         )



wallet.sync(blockchain, None)
balance = wallet.get_balance()
print(f"Wallet balance is: {balance.total}")


for tx in wallet.list_transactions(True):
    print(tx.confirmation_time.height,  datetime.datetime.fromtimestamp(tx.confirmation_time.timestamp).strftime("%Y-%m-%d %H:%M") , tx.txid)

```
    
    
this gives

![image](https://github.com/cculianu/Fulcrum/assets/116060138/853660e9-d079-41aa-90e0-8a71ad07718c)

where the marked row 
has the time: 2023-01-18 06:25

However it [should be](https://mempool.space/tx/4cd97314a596200e4c1f89fe9117c7dd8ebd7219d96165e9581803eaa18b4140) 2023-09-24 13:57   

The row above the marked one has however the correct timestamp.  This timestamp bug is likely not in bdkpython, since it disappears if fulcrum is replaced by electrs.

##### the error is not determinstic, with repeated executions I get different timestamps
![image](https://github.com/cculianu/Fulcrum/assets/116060138/a661458b-63ae-42b2-8eeb-c6732ee716bb)
![image](https://github.com/cculianu/Fulcrum/assets/116060138/cec65892-f656-426c-9409-7271d383f4bb)
![image](https://github.com/cculianu/Fulcrum/assets/116060138/3a60fb37-b797-4155-86cf-370495a8f461)
and it appears to happen to random transactions 
![image](https://github.com/cculianu/Fulcrum/assets/116060138/b29a1b80-8581-4447-a3bf-e07c483fdac2)
and it appears that the timestamps are mixed up between the different txs
![image](https://github.com/cculianu/Fulcrum/assets/116060138/47b2ff95-c545-4ab9-ad45-80a362f1e998)

------------------------
Fulcrum version:   1.9.7

**Comment by andreasgriffin** [comment]
It gets weirder:  If I fetch the transaction directly 

```python

import socket
import json

def fetch_transaction(txid):
    host = 'my_fulcrum_server'
    port = 50001
    
    # Create a socket connection
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(10)
    
    # Connect to the server
    s.connect((host, port))
    
    # Prepare the JSON-RPC payload for fetching the transaction
    payload = {
        "jsonrpc": "2.0",
        "id": 0,
        "method": "blockchain.transaction.get",
        "params": [txid, True],  # True for verbose output
    }
    message = json.dumps(payload) + '\n'
    
    # Send the request
    s.sendall(message.encode('utf-8'))
    
    # Receive the response
    response = s.recv(65535).decode('utf-8')  # Increased buffer size to ensure large transactions can be received
    
    # Close the socket
    s.close()
    
    # Parse and return the response
    return json.loads(response)

# Example usage
txid = '4cd97314a596200e4c1f89fe9117c7dd8ebd7219d96165e9581803eaa18b4140'  
transaction_info = fetch_transaction(txid)
print(transaction_info)

```

I get the correct timestamp  `1695556676`    `datetime.datetime(2023, 9, 24, 13, 57, 56)`.

**Comment by cculianu** [comment]
I don’t k know what all this is man.

fulcrum doesn’t do anything with timestamps it simply returns blockchain data faithfully

**Comment by andreasgriffin** [comment]
Yes, the more I find about this bug, the more I get the impression it is a rust-electrum-client  batching problem (that occurs with fulcrum, but not with electrs). 

I close this issue and copy the content over to https://github.com/bitcoindevkit/rust-electrum-client/issues/129

**Comment by cculianu** [comment]
Hmm. Yeah maybe a bug with the rust client. Maybe the rust client is assuming batches come back in the original request order. Fulcrum delivers batching results in a potentially out-of-order way (which is ok as far as the JSON-RPC spec says!).
