### ISSUE TITLE
Version v1.10.0 is missing in Docker Hub

### ISSUE THREAD

**Issue by thevops** [cculianu/Fulcrum#236]
https://hub.docker.com/r/cculianu/fulcrum/tags

It looks like GitHub Actions didn't execute the job for publishing the image - https://github.com/cculianu/Fulcrum/actions

**Comment by cculianu** [comment]
Oops. Will do the action now. I always forget this... sorry.

**Comment by cculianu** [comment]
Ok, I ran the publish action workflow.. closing.
