### ISSUE TITLE
Fulcrum

### ISSUE THREAD

**Issue by 94057** [cculianu/Fulcrum#239]
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.3> Got unexpected content type: text/html; charset=ISO-8859-1; will log the rest of this HTTP response
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.3> 401 (header):
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.3> 401 (content):
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.3> Error processing data coming in: Failed to parse Json from string:
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.288] <BitcoinD.2> 401 (header): Date: Wed, 27 Mar 2024 03:15:48 GMT
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> 401 (header): Content-Length: 0
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> 401 (header): Content-Type: text/html; charset=ISO-8859-1
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> Got unexpected content type: text/html; charset=ISO-8859-1; will log the rest of this HTTP response
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> 401 (header):
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> 401 (content):
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.290] <BitcoinD.2> Error processing data coming in: Failed to parse Json from string:
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.290] <BitcoinD.3> Lost connection to bitcoind, will retry every 5 seconds ...
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.290] <BitcoinD.2> Lost connection to bitcoind, will retry every 5 seconds ...
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.035] <Controller> Waiting for bitcoind...
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> Got HTTP status 401 Unauthorized; will log the rest of this HTTP response
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> Authentication to bitcoind rpc failed. Please check the rpcuser and rpcpass are correct and restart!
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (header): WWW-Authenticate: Basic realm="jsonrpc"
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (header): Date: Wed, 27 Mar 2024 03:15:53 GMT
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (header): Content-Length: 0
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (header): Content-Type: text/html; charset=ISO-8859-1
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> Got unexpected content type: text/html; charset=ISO-8859-1; will log the rest of this HTTP response
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (header):
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (content):
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> Error processing data coming in: Failed to parse Json from string:
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.289] <BitcoinD.1> Lost connection to bitcoind, will retry every 5 seconds ...
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.291] <BitcoinD.3> Got HTTP status 401 Unauthorized; will log the rest of this HTTP response
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.291] <BitcoinD.3> Authentication to bitcoind rpc failed. Please check the rpcuser and rpcpass are correct and restart!
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.291] <BitcoinD.3> 401 (header): WWW-Authenticate: Basic realm="jsonrpc"
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.291] <BitcoinD.3> 401 (header): Date: Wed, 27 Mar 2024 03:15:53 GMT
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.291] <BitcoinD.3> 401 (header): Content-Length: 0
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.291] <BitcoinD.3> 401 (header): Content-Type: text/html; charset=ISO-8859-1
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.291] <BitcoinD.3> Got unexpected content type: text/html; charset=ISO-8859-1; will log the rest of this HTTP response

Got unexpected content type: text/html; charset=ISO-8859-1; will log the rest of this HTTP response
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.3> 401 (header):ing data comin
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.3> 401 (content):n to bitcoind
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.3> Error processing data comin                                                                                                                                    g in: Failed to parse Json from string:[2024-03-27 03:15:53.294] <BitcoinD.2> Authentication to bitcoind
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.288] <BitcoinD.2> 401 (header): Date: Wed, 27                                                                                                                                     Mar 2024 03:15:48 GMTx Fulcrum[1741]: [2024-03-27 03:15:53.294] <BitcoinD.2> 401 (header): Date: Wed, 27
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> 401 (header): Content-Lengt                                                                                                                                    h: 027 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.294] <BitcoinD.2> 401 (header): Content-Type:
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> 401 (header): Content-Type:                                                                                                                                     text/html; charset=ISO-8859-1m[1741]: [2024-03-27 03:15:53.294] <BitcoinD.2> 401 (header):
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> Got unexpected content type                                                                                                                                    : text/html; charset=ISO-8859-1; will log the rest of this HTTP responsenD.2> Error processing data comin
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> 401 (header):on to bitcoind
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.289] <BitcoinD.2> 401 (content):s 401 Unautho
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.290] <BitcoinD.2> Error processing data comin                                                                                                                                    g in: Failed to parse Json from string:[2024-03-27 03:15:58.286] <BitcoinD.3> 401 (header): WWW-Authentic
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.290] <BitcoinD.3> Lost connection to bitcoind                                                                                                                                    , will retry every 5 seconds ...1741]: [2024-03-27 03:15:58.286] <BitcoinD.3> 401 (header): Content-Lengt
Mar 27 03:15:48 nodebox Fulcrum[1741]: [2024-03-27 03:15:48.290] <BitcoinD.2> Lost connection to bitcoind                                                                                                                                    , will retry every 5 seconds ...1741]: [2024-03-27 03:15:58.287] <BitcoinD.3> Got unexpected content type
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.035] <Controller> Waiting for bitcoind...
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> Got HTTP status 401 Unautho                                                                                                                                    rized; will log the rest of this HTTP response3-27 03:15:58.287] <BitcoinD.3> Error processing data comin
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> Authentication to bitcoind                                                                                                                                     rpc failed. Please check the rpcuser and rpcpass are correct and restart!D.1> Authentication to bitcoind
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (header): WWW-Authentic                                                                                                                                    ate: Basic realm="jsonrpc"lcrum[1741]: [2024-03-27 03:15:58.287] <BitcoinD.1> 401 (header): Date: Wed, 27
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (header): Date: Wed, 27                                                                                                                                     Mar 2024 03:15:53 GMTx Fulcrum[1741]: [2024-03-27 03:15:58.287] <BitcoinD.1> 401 (header): Content-Lengt
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (header): Content-Lengt                                                                                                                                    h: 0
Mar 27 03:15:53 nodebox Fulcrum[1741]: [2024-03-27 03:15:53.288] <BitcoinD.1> 401 (header): Content-Type:                                                                                                                                    ^C                          will retry every 5 seconds ...

**Comment by cculianu** [comment]
?

**Comment by 94057** [comment]
Not understanding why the fulcrum isn't working properly.

check the rpcuser and rpcpass are correct and restart!D ------ Which has been done already and still nothing.
