### ISSUE TITLE
IPv6 addresses should be formatted differently

### ISSUE THREAD

**Issue by georgengelmann** [cculianu/Fulcrum#242]
The output of FulcrumAdmin -p sessions returns
**2001:44b8:315f:bc00:1f7b:dcc3:8823:722d:60000**

It should return
**[2001:44b8:315f:bc00:1f7b:dcc3:8823:722d]:60000**

The last part is the port - it's easier to parse the data with [] as a separator.

**Comment by cculianu** [comment]
Ok, fixed in master.. Note that for you to see this change you either need to build it or.. wait for a release.
