### ISSUE TITLE
Latest release commit was signed with a different gpg key

### ISSUE THREAD

**Issue by dipunm** [cculianu/Fulcrum#245]
I am using this guide to install and verify Fulcrum: https://microbolt.guide/en-US/bitcoin/electrum-server/fulcrum

The last commit on v1.10.0 was done on Github with a different GPG key than other releases and other commits. What can we do to resolve this?

**Comment by dipunm** [comment]
Related: https://github.com/microbolt-guide/microbolt/issues/1

**Comment by cculianu** [comment]
This is because v1.10.0 was the result of a github merge.  It was signed by github, I guess, and not by me. 

I didn't realize anybody was verifying commits..
