### ISSUE TITLE
BTC testnet4 support

### ISSUE THREAD

**Issue by jlopp** [cculianu/Fulcrum#249]
FYI testnet3 is being deprecated; you can find the parameters for testnet4 here: https://github.com/bitcoin/bitcoin/pull/29775

**Comment by cculianu** [comment]
Ah thanks for the heads-up.  Yeah we in BCH also deprecated our testnet3 and are onto testnet4. Good to see the BTC people are doing similar.  I'll look at their changes and add BTC testnet4 soon, if they didn't do anything crazy ...

**Comment by cculianu** [comment]
Oh ok I just noticed they haven't merged this yet but it looks essentially very compatible with existing testnet3, so it should be no problem to add support for this to Fulcrum.  I will do so as soon as they merge this and/or plan a release containing it.

Thanks again for the heads-up. I will leave this issue open to remind myself to indeed add this to Fulcrum.

**Comment by jlopp** [comment]
Yeah it's not finalized yet but I think it's pretty close.

**Comment by cculianu** [comment]
Sounds good I’m traveling now but I’ll add support once I get back and have it ready for once they merge. Good stuff again thanks for the heads up!

**Comment by ast261** [comment]
"I will do so as soon as they merge this"

It's done.

**Comment by twofaktor** [comment]
Testnet4 on Fulcrum has been working for almost a month for me using the 1.11.0 version code:

![imagen](https://github.com/user-attachments/assets/1ffeb7df-4e82-4836-ab77-4a28ddd82c57)

And this config:

![imagen](https://github.com/user-attachments/assets/19f95d69-61ac-40da-806b-bb29f670c312)

No code modifications are needed

**Comment by cculianu** [comment]
Oh yeah sorry I forgot to announce it -- I indeed added support for it! I guess I can close this issue now.

**Comment by twofaktor** [comment]
> Oh yeah sorry I forgot to announce it -- I indeed added support for it! I guess I can close this issue now.

4 years ago 😁:

https://github.com/cculianu/Fulcrum/pull/50

**Comment by cculianu** [comment]
Oh no that was for BCH (we did test4 on BCH 4 years ago back in COVID times).  Hmm. Actually I realized that if you have `peering=true` it will fail right now on BTC because there is no server seed list for BTC test4. I need to implement that ASAP. I'm re-opening this issue.

**Comment by cculianu** [comment]
Ok, peering support has been added, so `peering=true` should work now on BTC testnet4. There is currently only 1 known Electrum server for testnet4, my own -- at blackie.c3-soft.com ssl port 57010, which has been compiled-in as the "seeding" node for peering.

**Comment by cculianu** [comment]
Let me know if you guys need a new release.. I figure there's no rush since Core hasn't released a binary with testnet4 yet, Electrum doesn't yet support it, etc... so i figured anybody interested can build Fulcrum from source now.. but let me know if you really really really want a release now that has this...

**Comment by twofaktor** [comment]
> if you really really really want a release now that has this...

It is not necessary at least for me, I can wait for the next Bitcoin Core release. Thanks for your implication 🙏

BTW: Testnet4 was recently merged -> https://github.com/bitcoin/bitcoin/pull/29775 🚀
