### ISSUE TITLE
Add FulcrumAdmin to the docker container to be able to gracefully shutdown Fulcrum

### ISSUE THREAD

**Issue by antonr-p2p** [cculianu/Fulcrum#253]
Please add FulcrumAdmin to the docker container to be able to gracefully shutdown Fulcrum.
Faced issue with corrupted DB, because used `kubectl delete pod fulcrum-0` today. 
Many times before it survived, but today faced corrupted data dir.
Once you would add FulcrumAdmin it would be possible to configure shutdown hook.

**Comment by cculianu** [comment]
Fulcrum responds to graceful shutdown signals that are standard such as SIGTERM and SIGINT.

just don’t kill it with SIGKILL.

Also provide a timeout to wait for graceful shutdown.

**Comment by cculianu** [comment]
I'll add the FulcrumAdmin script to the built image. The fact that it's missing is indeed an error. I think python3 also needs to be installed for it to work but that shouldn't be a problem.

**Comment by cculianu** [comment]
Ok, added to image. I will do a release very soon (v. 1.11.0 -- good stuff coming!). I will see if I can do a github action now to publish the new image tho.

**Comment by antonr-p2p** [comment]
@cculianu thanks a lot for a quick response and actions!
In a meantime I would try to use terminationGracePeriodSeconds option, I hope it would help.

**Comment by antonr-p2p** [comment]
BTW, Kubernetes send SIGTERM  and waits 30 seconds by default, then only SIGKILL. This delay can be configured via terminationGracePeriodSeconds . My issue was that I provided too small memory for both DB and container itself, so it crashed and had DB corrupted. Once I gave enough memory - I had no issue so far.
