### ISSUE TITLE
WebSocket support for Firefox requests

### ISSUE THREAD

**Issue by EchterAgo** [cculianu/Fulcrum#36]
Turns out Firefox starts WebSockets with an undefined HTTP version, which breaks the connection to Fulcrum:

```
GET / undefined
Host: bch.loping.net:50004
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: http://localhost:3000
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: K716Hio2iYwR9C1xVpronw==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

See https://github.com/cculianu/Fulcrum/blob/master/src/WebSocket.cpp#L517 and https://gitlab.com/GeneralProtocols/electrum-cash/-/merge_requests/16

**Comment by EchterAgo** [comment]
I just tested https://www.websocket.org/echo.html in Firefox and it sends HTTP/1.1 to that server.

**Comment by cculianu** [comment]
If I were to tolerate undefined or garbage version do you think that would fix it?

**Comment by EchterAgo** [comment]
The problem is very weird. I tried to figure out why Firefox is doing this but the codebase is huge. I'll try building Firefox to run with a debugger.

It sends `HTTP/1.1` to some servers, `undefined` to others. For example it sends `undefined` to `ws://bch.loping.net:50003/`,  `wss://bch.loping.net:50004/`,  `wss://bch.loping.net/`, but `HTTP/1.1` to `ws://bch.loping.net/`, it just doesn't make any sense.

There seems to be also another issue where Fulcrum rejects `Connection: keep-alive, Upgrade`: https://github.com/cculianu/Fulcrum/blob/master/src/WebSocket.cpp#L797

**Comment by EchterAgo** [comment]
Ok, I figured it out. The `HTTP/1.1` / `undefined` stuff is bullshit and only caused by the inspector. The client actually always sends the correct HTTP version, so the only issue is the `Connection` header check.

**Comment by cculianu** [comment]
I can make the connection check more permissive.  I may have not implemented that correctly actually.
