### ISSUE TITLE
Do not fallback to TLS v1.1 or TLS v1.0 [SSL & WSS]

### ISSUE THREAD

**Issue by georgengelmann** [cculianu/Fulcrum#42]
**IETF has already deprecated all SSL protocols, TLS 1.0, and TLS 1.1**

Fulcrum still supports TLS v1.1 and TLS v1.0 - all modern browsers are supporting TLS v1.2+

Changing the following line in websocket.cpp & Servers.cpp from:

`socket->setProtocol(QSsl::SslProtocol::AnyProtocol);`

to:

`socket->setProtocol(QSsl::SslProtocol::TlsV1_2OrLater);`

should work (untested)

**TLS supported versions test:** 

Try https://bch.loping.net:50002 or https://bch.loping.net:50004 in https://www.cdn77.com/tls-test

**Comment by cculianu** [comment]
My fear is that some old crappy client may fail to connect... 

Let me test this setting when I get back and see what I can do. Yes, I too hate deprecated insecure protocols ...

**Comment by cculianu** [comment]
Ok, I did some research. I’m not exactly sure if I understand it 100% correctly so please correct me if I am wrong but this is the summary:

It seems there’s nothing insecure about tls 1.1 — it’s just old and lacks advanced features so there has been a push for years to deprecate it.

Tls 1.0 also is secure but it supports negotiated fallback to SSL 3.0 which apparently has some holes.

I’ll do more research but I’m not terribly compelled to remove support for them.

What’s the motivation to restrict to the newer ones only? Is the current setup breaking this for you?

I could add a flag to config and CLI to optionally require tls1.1 or above if you want. How does that sound?

**Comment by georgengelmann** [comment]
> What’s the motivation to restrict to the newer ones only? Is the current setup breaking anything for you? Or do you just want things to be perfect?

Nothing is breaking, this is not high priority. Yes, I want things to be perfect (using newer protocols only): https://tools.ietf.org/id/draft-ietf-tls-oldversions-deprecate-02.html

>My fear is that some old crappy client may fail to connect...

I don't think it is a problem now - TLSv1.2 was added for Windows 7 in **2009**

**Comment by cculianu** [comment]
What about Windows XP? :)

How would you feel if I introduce it as an option (off by default) -- and you can enable it on your server?

**Comment by cculianu** [comment]
This has now been addressed in 9c41a8a
