### ISSUE TITLE
FATAL: Cannot seek to write header

### ISSUE THREAD

**Issue by infertux** [cculianu/Fulcrum#60]
I'm trying to set up a new Fulcrum instance but it keeps crashing around block height 426k. I tried to remove `/var/lib/fulcrum/datadir/` then sync again but that didn't help.

```
Fulcrum[24411]: [2020-09-10 15:49:39.361] <Controller> Processed height: 425000, 65.2%, 4.10 blocks/sec, 6282.7 txs/sec, 22033.2 addrs/sec
Fulcrum[24411]: [2020-09-10 15:53:20.802] <Controller> Processed height: 426000, 65.3%, 4.51 blocks/sec, 7058.6 txs/sec, 24676.1 addrs/sec
Fulcrum[24411]: [2020-09-10 15:54:54.765] <Controller> FATAL: Cannot seek to write header for /var/lib/fulcrum/datadir/txnum2txhash
Fulcrum[24411]: [2020-09-10 15:54:54.766] (Debug) void App::cleanup()
Fulcrum[24411]: [2020-09-10 15:54:54.767] Stopping Stats HTTP Servers ...
```

Any ideas?

**Comment by cculianu** [comment]
Hmm.. weird. I guess the obvious question(s) are:

1. Is that a 64-bit filesystem?  Can it handle file sizes beyond 4GB?  The `txnum2txhash` file alone is 9GB for me on mainnet.
2. Does the filesystem in question have enough space? Something like 33-40GB is needed.

**Comment by infertux** [comment]
1. The filesystem is [XFS](https://en.wikipedia.org/wiki/XFS). My `txnum2txhash` file is 4.6GB.
2. There is ~120GB of free space.

So everything looks good on that front.

Can I increase the log verbosity somehow?

**Comment by cculianu** [comment]
Ok so it broke past the 4.3 GB limit.  Hmm. I don't think much logging happens for that subsystem -- that's a fairly low-level thing. Literally it seeks and tries to write and fails.  Very strange.

I am out of ideas tbh.  I have never seen this before. 

You can try `strace` to get a system call trace and see exactly why the seek system call is failing there.

Did you build Fulcrum yourself? Or is it the static binary I ship?

**Comment by infertux** [comment]
Hold on, the filesystem in question might have had less than 120GB of free space when the crash actually happened. I'll try a fresh sync from scratch and report back...

**Comment by cculianu** [comment]
Ha ha yeah ok. Hopefully that's it!

**Comment by infertux** [comment]
It's still syncing past block 426k now so I think another program was using a bunch of disk space when Fulcrum crashed. Sorry for the false alarm. Maybe Fulcrum could check there is enough free space as the "Cannot seek to write header" error message wasn't clear to me but that's just a nice-to-have thing :)

**Comment by cculianu** [comment]
Yeah I guess a thing to do there when it fails is check disk space as a diagnostic helper.  I'll keep that in mind.
