### ISSUE TITLE
Can't use hostname in tor_proxy

### ISSUE THREAD

**Issue by Mave95** [cculianu/Fulcrum#71]
It's not possible to define tor_proxy with a hostname instead of an IP. This is especially needed for Docker, when you define a tor service and don't know it's IP.

**Comment by cculianu** [comment]
Ah. Ha -- it never occurred to me somebody would need that.  Ok, yeah I can fix that.

**Comment by Mave95** [comment]
Each container has it's own IP. When using 127.0.0.1 you would have to run tor in the same container or use "--network host" for both the tor and Fulcrum container.

**Comment by cculianu** [comment]
Gotcha -- @EchterAgo had a similar issue with another of the params and I ended up adding hostname support there. Will add this now -- hopefully it won't be too much code change.  Looking at it now.

**Comment by Mave95** [comment]
Works as expected. Thanks.
