### ISSUE TITLE
Add option to use `.cookie` file

### ISSUE THREAD

**Issue by ejose19** [cculianu/Fulcrum#79]
It would be great if `Fulcrum` could read from the cookie file instead of using rpc credentials, as it saves the user from managing another pair of credentials by relying on directory permissions.

**Comment by cculianu** [comment]
Hmm.. I'll have to look at that auth scheme and how it works.  I understand that's actually preferred nowadays, right? This is a good suggestion -- I'll look into it and perhaps do it Thanks!

**Comment by ejose19** [comment]
Yes, both `electrs` and `electrum-personal-server` uses cookie method, which is the preferred way: [[1]](https://github.com/romanz/electrs/blob/master/doc/usage.md#bitcoind-configuration) [[2]](https://github.com/chris-belcher/electrum-personal-server/blob/d31fa2d0ab47cb0d3d0d0f071e00fe90d247e603/config.ini_sample#L22-L31) [[3]](https://github.com/Kixunil/security_writings/blob/master/cookie_files.md)

**Comment by cculianu** [comment]
Hmm -- ok. Yeah I just did some research on this.  Apparently under-the-hood the .cookie file and the user:pass mechanism end up identical on the HTTP layer.  This is good.  I can easily do this.  Consider this a feature I will work on soon.  Thanks for the tip and the heads-up on it.

**Comment by cculianu** [comment]
Hi @ejose19 -- do you know how to build Fulcrum from source?  If so can you pull latest master and try out the new `.cookie` file feature? It has been added in this commit: 3fc0a85f03ceaf9d1094ce357f8c4f03426762ce

Let me know how you like it and/or if it works as expected.  (I'm testing it now with BCHN on BCH and it works great.)

**Comment by cculianu** [comment]
Ok, well I have been testing this here and it's working (using BCHN on BCH).  I will close this issue since it is implemented in latest master.  If you want me to shoot you a pre-built static binary off master just let me know.

Or if you encounter problems with this feature now, re-open the issue or write here or create a new issue.

Thanks @ejose19 for the suggestion!

**Comment by ejose19** [comment]
Also tested with BCHN and it works great, I was preparing a PR to improve the error message when the cookie load had an issue, I'm using docker build but it seems it's rebuilding `jemalloc` & `rocksdb` every time, is there an argument to skip rebuilding of those 2 and just go straight to `Fulcrum` build?

**Comment by cculianu** [comment]
Great, thanks for testing and confirming it works.
