### ISSUE TITLE
FIXME: dsp addTx returned false for dspHash

### ISSUE THREAD

**Issue by jkister** [cculianu/Fulcrum#90]
Just saw some weird logs.  Nothing appears to be broken. 

> &lt;SynchMempool> addNewTxs: dsp addTx returned false for dspHash: 0077b5e7727615c07cd11a9f4ea2dc9189d8f1f775325dd6d27a2beb0a594c96, txid: 9a3cbbd258ab7006b0c095d105337497acdafc1fd572cf8a3a2143bf0275ae34. FIXME!

> &lt;SynchMempool> addNewTxs: dsp addTx returned false for dspHash: 97c5d6897c2cab2fefeb9d81d3edfc951f8f492bba960b25ec338d0e3e82846c, txid: 9a3cbbd258ab7006b0c095d105337497acdafc1fd572cf8a3a2143bf0275ae34. FIXME!

> &lt;SynchMempool> addNewTxs: dsp addTx returned false for dspHash: 4d4e481d37c37688d167e434226e09a47d68bb94db8fbafef1dfeba367493a3b, txid: 9a3cbbd258ab7006b0c095d105337497acdafc1fd572cf8a3a2143bf0275ae34. FIXME!

> Fulcrum 1.5.2 (Release f340a65)

**Comment by cculianu** [comment]
Dude, you're awesome for reporting this! I noticed this too the other day and fixed this in latest commit. It's a spurious/wrong warning and can be safely ignored. Fixed here: https://github.com/cculianu/Fulcrum/commit/781b4031fbb32c050765afcd565037ad582d3001

**Comment by cculianu** [comment]
I'm closing as already fixed. But I do thank you for reporting.  Seems we both saw the same unlikely situation in the logs. You can ignore the warning for now.. or if you know how to, build latest master and the warning will no longer appear unless *REALLY* an invariant is violated.
